version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - testdata
    - vendor