AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vulnly API - Vulnerability Scanner Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - arm64

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  VulnlyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: .
      Handler: bootstrap
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          USERS_TABLE: !Ref UsersTable
          PROJECTS_TABLE: !Ref ProjectsTable
          SCANS_TABLE: !Ref ScansTable
          VULNERABILITIES_TABLE: !Ref VulnerabilitiesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ScansTable
        - DynamoDBCrudPolicy:
            TableName: !Ref VulnerabilitiesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref VulnlyApi

  VulnlyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowOrigin: "'http://localhost:3000'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub vulnly-users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub vulnly-projects-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: projectId
          KeyType: RANGE

  ScansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub vulnly-scans-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: scanId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: scanId
          KeyType: RANGE

  VulnerabilitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub vulnly-vulnerabilities-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: scanId
          AttributeType: S
        - AttributeName: vulnId
          AttributeType: S
      KeySchema:
        - AttributeName: scanId
          KeyType: HASH
        - AttributeName: vulnId
          KeyType: RANGE

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${VulnlyApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt VulnlyFunction.Arn